### ISSUE TITLE
建议章节设计中添加更多的跟链接性相关的开发例子

### ISSUE THREAD

**Issue by n5ken** [nladuo/IOT-firstep#2]
物联网一方面需要接入网络，另一方面需要使用到大量的传感器，实际上安卓与iOS的教程已经铺天盖地，因此没必要花太多时间在移动端的部分，更加快章节举例说明如何集成4G、Wi-Fi、Bluetooth、433、声、温、光感等。

**Comment by nladuo** [comment]
听了你的建议，我决定移除iOS的部分😂。Android的部分之前是用eclipse写的，现在打算转为Android studio。

传感器的话主要是涉及到时序的操作或者是库的使用，这篇教程一是总结我大学的所学，二是介绍几个简单而不复杂的例子，所以只会涉及到一个BLE的例子，以及一个网络模块的使用。

**Comment by daruo** [comment]
为什么要移除iOS，不理解！鄙人不才，愿请缨提供写蓝牙模块iOS的材料


发自网易邮箱大师
在2017年03月27日 17:17，Kalen Blue 写道：

听了你的建议，我决定移除iOS的部分😂。Android的部分之前是用eclipse写的，现在打算转为Android studio。

传感器的话主要是涉及到时序的操作或者是库的使用，这篇教程一是总结我大学的所学，二是介绍几个简单而不复杂的例子，所以只会涉及到一个BLE的例子，以及一个网络模块的使用。

**Comment by nladuo** [comment]
我iOS是半吊子学的，我一会儿建个微信群吧。

**Comment by daruo** [comment]
嗯嗯，严重支持！


发自网易邮箱大师
在2017年03月27日 17:59，Kalen Blue 写道：

我iOS是半吊子学的，我一会儿建个微信群吧。

**Comment by nladuo** [comment]
群二维码：
![](http://nladuo.github.io/issue_imgs/IoT-Firstep_2/wechat2.jpeg)

**Comment by n5ken** [comment]
二维码实效了

**Comment by nladuo** [comment]
已更新
