### ISSUE TITLE
GoLang环境配置时候出现了问题

### ISSUE THREAD

**Issue by ghost** [nladuo/IOT-firstep#3]
按照教程所示，配置好了Golang的基本环境，但是在Sublime中根本添加不到教程所说的Go Sublime，不知道是什么原因

**Comment by nladuo** [comment]
我看一下

**Comment by nladuo** [comment]
之前是第一章的教程介绍的是NodeMCU，里面介绍过安装Sublime Text。需要先安装Package Control。我把这块补上去。

**Comment by ghost** [comment]
嗯呢～

**Comment by nladuo** [comment]
你再看一下，[安装sublime-text3和package-control](https://github.com/nladuo/IoT-Firstep/blob/master/book/5.1.md#安装sublime-text3和package-control)

**Comment by ghost** [comment]
嗯呢
