### ISSUE TITLE
教程缺少设备之间的连接问题

### ISSUE THREAD

**Issue by Xlinlin** [nladuo/IOT-firstep#6]
教程缺少一些设备之间的连接说明，作为完全的小白，现在买到楼主所说的一些小件不知道怎么串起来。开发版和ttl都不知道怎么串了/捂脸

**Comment by nladuo** [comment]
哪个没有写？

**Comment by Xlinlin** [comment]
我用的Nano V3.0 ft232模块 RS346板子 + USB TO TTL连接， ttl 的 5V连接nano的5V  txd连接rxd rxd连接txd gnd连接gnd，这个连接方式找了好久才找出来。连接后上传代码出现了错误：avrdude stk500_getsync() not in sync resp=0x30。想请问下你当时的场景以及我的连接方式有问题吗？

**Comment by nladuo** [comment]
上传代码的时候不要连接串口。上传完代码再连接。
